// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ0GWJNV17i1cnbE2cA19PD3DbYFMbfQM',
    appId: '1:582358536784:web:5c20f22b2d0c7745b97755',
    messagingSenderId: '582358536784',
    projectId: 'jansen-iot',
    authDomain: 'jansen-iot.firebaseapp.com',
    databaseURL: 'https://jansen-iot-default-rtdb.firebaseio.com',
    storageBucket: 'jansen-iot.appspot.com',
    measurementId: 'G-1EWVPF1HT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8shCRbMwwXjmYHD21K3IIfCeOGkoYA2w',
    appId: '1:582358536784:android:8bb96bd8eacf95aeb97755',
    messagingSenderId: '582358536784',
    projectId: 'jansen-iot',
    databaseURL: 'https://jansen-iot-default-rtdb.firebaseio.com',
    storageBucket: 'jansen-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5iH32cQWxR1vdJypSB49zTA4si6yH--g',
    appId: '1:582358536784:ios:bc20fdfbe0f4f55db97755',
    messagingSenderId: '582358536784',
    projectId: 'jansen-iot',
    databaseURL: 'https://jansen-iot-default-rtdb.firebaseio.com',
    storageBucket: 'jansen-iot.appspot.com',
    iosClientId: '582358536784-5031rk37m60jk8do673mbham5950ad29.apps.googleusercontent.com',
    iosBundleId: 'com.example.testtrmade1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5iH32cQWxR1vdJypSB49zTA4si6yH--g',
    appId: '1:582358536784:ios:bc20fdfbe0f4f55db97755',
    messagingSenderId: '582358536784',
    projectId: 'jansen-iot',
    databaseURL: 'https://jansen-iot-default-rtdb.firebaseio.com',
    storageBucket: 'jansen-iot.appspot.com',
    iosClientId: '582358536784-5031rk37m60jk8do673mbham5950ad29.apps.googleusercontent.com',
    iosBundleId: 'com.example.testtrmade1',
  );
}
